title: The HarpsCloud
description: >
  Documentation and ramblings for my home automation and other personal technology projects.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.theharps.cloud" # the base hostname & protocol for your site, e.g. http://example.com

author: Daniel Harp
author-img: profile-image.jpg
about-author: > 
  I am a director of software engineering with passion for continuous learning and improvement.
  TheHarpsCloud refers to my local homelab, my "local cloud", i.e. The Harps' cloud.
social-github: hrhdaniel # add your Github handle
social-linkedin: danielrharp # add your Linkedin handle
social-email: blog@theharps.cloud # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
# analytics: # Google Analytics

# Build Settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
